#!/bin/sh
export IDEA_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/idea.vmoptions"
export CLION_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/clion.vmoptions"
export PHPSTORM_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/phpstorm.vmoptions"
export GOLAND_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/goland.vmoptions"
export PYCHARM_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/pycharm.vmoptions"
export WEBSTORM_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/webstorm.vmoptions"
export WEBIDE_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/webide.vmoptions"
export RIDER_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/rider.vmoptions"
export DATAGRIP_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/datagrip.vmoptions"
export RUBYMINE_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/rubymine.vmoptions"
export APPCODE_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/appcode.vmoptions"
export DATASPELL_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/dataspell.vmoptions"
export GATEWAY_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/gateway.vmoptions"
export JETBRAINS_CLIENT_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/jetbrains_client.vmoptions"
export JETBRAINSCLIENT_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/jetbrainsclient.vmoptions"
export STUDIO_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/studio.vmoptions"
export DEVECOSTUDIO_VM_OPTIONS="/home/whale/Applications/ja-netfilter-modified/vmoptions/devecostudio.vmoptions"
